/**
 * Crops the studio shots to the product, for the hero stage.
 *
 * The masters are chairs on a white sweep with a wide white margin — often a third of the frame.
 * Staged at hero size that margin shrank every chair to a stamp inside its own card, which is
 * what made the line-up look empty. Trimming the sweep back to the product lets the same card
 * show a chair two to three times larger with no other change.
 *
 * Transparency was the other route and it is not worth it: these are lossy WebP masters, and the
 * compression halo around a black chair on white sits at a luminance the mask cannot separate
 * from a pale grey armrest — every threshold that removed the halo also ate the light models.
 * So the ground stays white and the stage puts each chair on a white card, which is how the
 * client's own artwork stages them anyway.
 *
 * Run: node scripts/hero-cutouts.mjs
 * Writes: public/hero/models/<slug>.webp  +  src/data/hero-cutouts.generated.ts
 */
import { readdir, mkdir, writeFile, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';

const ROOT = process.cwd();
const SRC = path.join(ROOT, 'public', 'products');
const OUT = path.join(ROOT, 'public', 'hero', 'models');
const MANIFEST = path.join(ROOT, 'src', 'data', 'hero-cutouts.generated.ts');

/** Tall enough for a retina hero card; the masters are 1100–1200px squares. */
const MAX_HEIGHT = 820;
/** A little white left around the product, so it never touches the card's edge. */
const PAD = 26;

async function crop(file, slug) {
  const base = sharp(file).rotate();
  const meta = await base.metadata();
  if (!meta.width) throw new Error('no dimensions');

  const trimmed = await base
    // threshold 8: the compression halo round a hard edge is not the sweep
    .trim({ background: '#ffffff', threshold: 8 })
    .toBuffer({ resolveWithObject: true });

  const out = await sharp(trimmed.data)
    .flatten({ background: '#ffffff' })
    .extend({ top: PAD, bottom: PAD, left: PAD, right: PAD, background: '#ffffff' })
    // width null: scale by height alone. `fit: 'inside'` with one dimension is a no-op in sharp,
    // which is why an earlier pass left 1000px+ files behind.
    .resize(null, MAX_HEIGHT, { withoutEnlargement: true })
    .webp({ quality: 88, effort: 5 })
    .toBuffer();

  await writeFile(path.join(OUT, `${slug}.webp`), out);
  const after = await sharp(out).metadata();
  return {
    slug,
    from: `${meta.width}x${meta.height}`,
    to: `${after.width}x${after.height}`,
    kb: Math.round(out.length / 1024),
    gain: `${Math.round((meta.width / (trimmed.info.width || meta.width)) * 100) / 100}x`,
  };
}

async function main() {
  // a previous pass wrote alpha versions here; clear the directory so nothing stale survives
  await rm(OUT, { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });
  if (!existsSync(SRC)) throw new Error('no public/products directory');

  const families = await readdir(SRC, { withFileTypes: true });
  const jobs = [];

  for (const family of families.filter((entry) => entry.isDirectory())) {
    const models = await readdir(path.join(SRC, family.name), { withFileTypes: true });
    for (const model of models.filter((entry) => entry.isDirectory())) {
      const dir = path.join(SRC, family.name, model.name);
      const shots = (await readdir(dir)).filter((name) => /\.(webp|png|jpe?g)$/i.test(name)).sort();
      // the first frame of the first colourway is the straight-on shot
      if (shots.length) jobs.push({ slug: model.name, file: path.join(dir, shots[0]) });
    }
  }

  const done = [];
  for (const job of jobs) {
    try {
      done.push(await crop(job.file, job.slug));
    } catch (error) {
      console.error(`  x ${job.slug}: ${error.message}`);
    }
  }

  done.sort((a, b) => a.slug.localeCompare(b.slug));
  const lines = done.map((row) => `  '${row.slug}': '/hero/models/${row.slug}.webp',`).join('\n');
  await writeFile(
    MANIFEST,
    `// GENERATED by \`node scripts/hero-cutouts.mjs\` — do not edit by hand.\n` +
      `// Studio shots cropped to the product, for staging at hero size.\n\n` +
      `export const HERO_CROPS: Record<string, string> = {\n${lines}\n};\n`,
    'utf8',
  );

  for (const row of done) console.log(`  ok ${row.slug.padEnd(18)} ${row.from} -> ${row.to}  ${row.kb}kb  (${row.gain} bigger)`);
  console.log(`\n${done.length} crops written to public/hero/models`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
