// GENERATED by `node scripts/hero-cutouts.mjs` — do not edit by hand.
// Studio shots cropped to the product, for staging at hero size.

export const HERO_CROPS: Record<string, string> = {
  'bonai-hb': '/hero/models/bonai-hb.webp',
  'bonai-mb': '/hero/models/bonai-mb.webp',
  'bubble-mb': '/hero/models/bubble-mb.webp',
  'comfort-hi-stool': '/hero/models/comfort-hi-stool.webp',
  'ecco-mb': '/hero/models/ecco-mb.webp',
  'eiffel-hb': '/hero/models/eiffel-hb.webp',
  'eiffel-mb': '/hero/models/eiffel-mb.webp',
  'feather-mb': '/hero/models/feather-mb.webp',
  'glanza-hb': '/hero/models/glanza-hb.webp',
  'glanza-mb': '/hero/models/glanza-mb.webp',
  'hilite-hb': '/hero/models/hilite-hb.webp',
  'hilite-mb': '/hero/models/hilite-mb.webp',
  'mustang-hb': '/hero/models/mustang-hb.webp',
  'mustang-mb': '/hero/models/mustang-mb.webp',
  'optimus-pre-hb': '/hero/models/optimus-pre-hb.webp',
  'optimus-pre-mb': '/hero/models/optimus-pre-mb.webp',
  'yaris-hb': '/hero/models/yaris-hb.webp',
  'yaris-mb': '/hero/models/yaris-mb.webp',
};
