// GENERATED by `npm run ingest-images` — do not edit by hand.
// Source: DecArt product photo-shoot masters.

export type ColourwayShots = { label: string; slug: string; images: string[] };
export type PhotoshootEntry = { model: string; back: string; family: string; colours: ColourwayShots[] };

export const PHOTOSHOOT: Record<string, PhotoshootEntry> = {
  "bonai-hb": {
    "model": "Bonai",
    "back": "HB",
    "family": "mesh",
    "colours": [
      {
        "label": "Black",
        "slug": "black",
        "images": [
          "/products/mesh/bonai-hb/black-1.webp",
          "/products/mesh/bonai-hb/black-2.webp",
          "/products/mesh/bonai-hb/black-3.webp",
          "/products/mesh/bonai-hb/black-4.webp",
          "/products/mesh/bonai-hb/black-5.webp"
        ]
      }
    ]
  },
  "bonai-mb": {
    "model": "Bonai",
    "back": "MB",
    "family": "mesh",
    "colours": [
      {
        "label": "Black",
        "slug": "black",
        "images": [
          "/products/mesh/bonai-mb/black-1.webp",
          "/products/mesh/bonai-mb/black-2.webp",
          "/products/mesh/bonai-mb/black-3.webp",
          "/products/mesh/bonai-mb/black-4.webp"
        ]
      }
    ]
  },
  "comfort-hi-stool": {
    "model": "Comfort Hi-Stool",
    "back": "",
    "family": "cafe",
    "colours": [
      {
        "label": "Blue",
        "slug": "blue",
        "images": [
          "/products/cafe/comfort-hi-stool/blue-1.webp",
          "/products/cafe/comfort-hi-stool/blue-2.webp",
          "/products/cafe/comfort-hi-stool/blue-3.webp"
        ]
      },
      {
        "label": "Green",
        "slug": "green",
        "images": [
          "/products/cafe/comfort-hi-stool/green-1.webp",
          "/products/cafe/comfort-hi-stool/green-2.webp",
          "/products/cafe/comfort-hi-stool/green-3.webp",
          "/products/cafe/comfort-hi-stool/green-4.webp"
        ]
      },
      {
        "label": "Orange",
        "slug": "orange",
        "images": [
          "/products/cafe/comfort-hi-stool/orange-1.webp",
          "/products/cafe/comfort-hi-stool/orange-2.webp",
          "/products/cafe/comfort-hi-stool/orange-3.webp",
          "/products/cafe/comfort-hi-stool/orange-4.webp"
        ]
      }
    ]
  },
  "ecco-mb": {
    "model": "Ecco",
    "back": "MB",
    "family": "task-mesh",
    "colours": [
      {
        "label": "Black",
        "slug": "black",
        "images": [
          "/products/task-mesh/ecco-mb/black-1.webp",
          "/products/task-mesh/ecco-mb/black-2.webp",
          "/products/task-mesh/ecco-mb/black-3.webp"
        ]
      }
    ]
  },
  "eiffel-hb": {
    "model": "Eiffel",
    "back": "HB",
    "family": "special-luxury-mesh",
    "colours": [
      {
        "label": "Black with Blue",
        "slug": "black-with-blue",
        "images": [
          "/products/special-luxury-mesh/eiffel-hb/black-with-blue-1.webp",
          "/products/special-luxury-mesh/eiffel-hb/black-with-blue-2.webp",
          "/products/special-luxury-mesh/eiffel-hb/black-with-blue-3.webp",
          "/products/special-luxury-mesh/eiffel-hb/black-with-blue-4.webp"
        ]
      },
      {
        "label": "Black with Green",
        "slug": "black-with-green",
        "images": [
          "/products/special-luxury-mesh/eiffel-hb/black-with-green-1.webp",
          "/products/special-luxury-mesh/eiffel-hb/black-with-green-2.webp",
          "/products/special-luxury-mesh/eiffel-hb/black-with-green-3.webp",
          "/products/special-luxury-mesh/eiffel-hb/black-with-green-4.webp"
        ]
      },
      {
        "label": "Black with Grey",
        "slug": "black-with-grey",
        "images": [
          "/products/special-luxury-mesh/eiffel-hb/black-with-grey-1.webp",
          "/products/special-luxury-mesh/eiffel-hb/black-with-grey-2.webp",
          "/products/special-luxury-mesh/eiffel-hb/black-with-grey-3.webp",
          "/products/special-luxury-mesh/eiffel-hb/black-with-grey-4.webp"
        ]
      },
      {
        "label": "Black with Orange",
        "slug": "black-with-orange",
        "images": [
          "/products/special-luxury-mesh/eiffel-hb/black-with-orange-1.webp",
          "/products/special-luxury-mesh/eiffel-hb/black-with-orange-2.webp",
          "/products/special-luxury-mesh/eiffel-hb/black-with-orange-3.webp",
          "/products/special-luxury-mesh/eiffel-hb/black-with-orange-4.webp"
        ]
      },
      {
        "label": "Black with Orange (2)",
        "slug": "black-with-orange-2",
        "images": [
          "/products/special-luxury-mesh/eiffel-hb/black-with-orange-2-1.webp"
        ]
      },
      {
        "label": "Black with Red",
        "slug": "black-with-red",
        "images": [
          "/products/special-luxury-mesh/eiffel-hb/black-with-red-1.webp",
          "/products/special-luxury-mesh/eiffel-hb/black-with-red-2.webp",
          "/products/special-luxury-mesh/eiffel-hb/black-with-red-3.webp",
          "/products/special-luxury-mesh/eiffel-hb/black-with-red-4.webp"
        ]
      },
      {
        "label": "Grey with Grey",
        "slug": "grey-with-grey",
        "images": [
          "/products/special-luxury-mesh/eiffel-hb/grey-with-grey-1.webp",
          "/products/special-luxury-mesh/eiffel-hb/grey-with-grey-2.webp",
          "/products/special-luxury-mesh/eiffel-hb/grey-with-grey-3.webp",
          "/products/special-luxury-mesh/eiffel-hb/grey-with-grey-4.webp"
        ]
      }
    ]
  },
  "eiffel-mb": {
    "model": "Eiffel",
    "back": "MB",
    "family": "special-luxury-mesh",
    "colours": [
      {
        "label": "Black with Blue",
        "slug": "black-with-blue",
        "images": [
          "/products/special-luxury-mesh/eiffel-mb/black-with-blue-1.webp",
          "/products/special-luxury-mesh/eiffel-mb/black-with-blue-2.webp",
          "/products/special-luxury-mesh/eiffel-mb/black-with-blue-3.webp",
          "/products/special-luxury-mesh/eiffel-mb/black-with-blue-4.webp"
        ]
      },
      {
        "label": "Black with Green",
        "slug": "black-with-green",
        "images": [
          "/products/special-luxury-mesh/eiffel-mb/black-with-green-1.webp",
          "/products/special-luxury-mesh/eiffel-mb/black-with-green-2.webp",
          "/products/special-luxury-mesh/eiffel-mb/black-with-green-3.webp",
          "/products/special-luxury-mesh/eiffel-mb/black-with-green-4.webp",
          "/products/special-luxury-mesh/eiffel-mb/black-with-green-5.webp",
          "/products/special-luxury-mesh/eiffel-mb/black-with-green-6.webp",
          "/products/special-luxury-mesh/eiffel-mb/black-with-green-7.webp",
          "/products/special-luxury-mesh/eiffel-mb/black-with-green-8.webp"
        ]
      },
      {
        "label": "Black with Grey",
        "slug": "black-with-grey",
        "images": [
          "/products/special-luxury-mesh/eiffel-mb/black-with-grey-1.webp",
          "/products/special-luxury-mesh/eiffel-mb/black-with-grey-2.webp",
          "/products/special-luxury-mesh/eiffel-mb/black-with-grey-3.webp",
          "/products/special-luxury-mesh/eiffel-mb/black-with-grey-4.webp"
        ]
      },
      {
        "label": "Black with Orange",
        "slug": "black-with-orange",
        "images": [
          "/products/special-luxury-mesh/eiffel-mb/black-with-orange-1.webp",
          "/products/special-luxury-mesh/eiffel-mb/black-with-orange-2.webp",
          "/products/special-luxury-mesh/eiffel-mb/black-with-orange-3.webp",
          "/products/special-luxury-mesh/eiffel-mb/black-with-orange-4.webp"
        ]
      },
      {
        "label": "Black with Red",
        "slug": "black-with-red",
        "images": [
          "/products/special-luxury-mesh/eiffel-mb/black-with-red-1.webp",
          "/products/special-luxury-mesh/eiffel-mb/black-with-red-2.webp",
          "/products/special-luxury-mesh/eiffel-mb/black-with-red-3.webp",
          "/products/special-luxury-mesh/eiffel-mb/black-with-red-4.webp"
        ]
      },
      {
        "label": "Grey with Grey",
        "slug": "grey-with-grey",
        "images": [
          "/products/special-luxury-mesh/eiffel-mb/grey-with-grey-1.webp",
          "/products/special-luxury-mesh/eiffel-mb/grey-with-grey-2.webp",
          "/products/special-luxury-mesh/eiffel-mb/grey-with-grey-3.webp",
          "/products/special-luxury-mesh/eiffel-mb/grey-with-grey-4.webp"
        ]
      }
    ]
  },
  "feather-mb": {
    "model": "Feather",
    "back": "MB",
    "family": "task-mesh",
    "colours": [
      {
        "label": "Black with Black",
        "slug": "black-with-black",
        "images": [
          "/products/task-mesh/feather-mb/black-with-black-1.webp",
          "/products/task-mesh/feather-mb/black-with-black-2.webp",
          "/products/task-mesh/feather-mb/black-with-black-3.webp",
          "/products/task-mesh/feather-mb/black-with-black-4.webp"
        ]
      },
      {
        "label": "Black with Blue",
        "slug": "black-with-blue",
        "images": [
          "/products/task-mesh/feather-mb/black-with-blue-1.webp",
          "/products/task-mesh/feather-mb/black-with-blue-2.webp",
          "/products/task-mesh/feather-mb/black-with-blue-3.webp",
          "/products/task-mesh/feather-mb/black-with-blue-4.webp",
          "/products/task-mesh/feather-mb/black-with-blue-5.webp",
          "/products/task-mesh/feather-mb/black-with-blue-6.webp"
        ]
      },
      {
        "label": "Black with Green",
        "slug": "black-with-green",
        "images": [
          "/products/task-mesh/feather-mb/black-with-green-1.webp",
          "/products/task-mesh/feather-mb/black-with-green-2.webp",
          "/products/task-mesh/feather-mb/black-with-green-3.webp",
          "/products/task-mesh/feather-mb/black-with-green-4.webp"
        ]
      },
      {
        "label": "Black with Grey",
        "slug": "black-with-grey",
        "images": [
          "/products/task-mesh/feather-mb/black-with-grey-1.webp",
          "/products/task-mesh/feather-mb/black-with-grey-2.webp",
          "/products/task-mesh/feather-mb/black-with-grey-3.webp",
          "/products/task-mesh/feather-mb/black-with-grey-4.webp",
          "/products/task-mesh/feather-mb/black-with-grey-5.webp"
        ]
      },
      {
        "label": "Black with Orange",
        "slug": "black-with-orange",
        "images": [
          "/products/task-mesh/feather-mb/black-with-orange-1.webp",
          "/products/task-mesh/feather-mb/black-with-orange-2.webp",
          "/products/task-mesh/feather-mb/black-with-orange-3.webp",
          "/products/task-mesh/feather-mb/black-with-orange-4.webp"
        ]
      },
      {
        "label": "Black with Red",
        "slug": "black-with-red",
        "images": [
          "/products/task-mesh/feather-mb/black-with-red-1.webp",
          "/products/task-mesh/feather-mb/black-with-red-2.webp",
          "/products/task-mesh/feather-mb/black-with-red-3.webp",
          "/products/task-mesh/feather-mb/black-with-red-4.webp"
        ]
      },
      {
        "label": "Black with Silver Grey",
        "slug": "black-with-silver-grey",
        "images": [
          "/products/task-mesh/feather-mb/black-with-silver-grey-1.webp",
          "/products/task-mesh/feather-mb/black-with-silver-grey-2.webp",
          "/products/task-mesh/feather-mb/black-with-silver-grey-3.webp"
        ]
      },
      {
        "label": "Grey with Grey",
        "slug": "grey-with-grey",
        "images": [
          "/products/task-mesh/feather-mb/grey-with-grey-1.webp",
          "/products/task-mesh/feather-mb/grey-with-grey-2.webp"
        ]
      }
    ]
  },
  "glanza-hb": {
    "model": "Glanza",
    "back": "HB",
    "family": "mesh",
    "colours": [
      {
        "label": "Grey",
        "slug": "grey",
        "images": [
          "/products/mesh/glanza-hb/grey-1.webp",
          "/products/mesh/glanza-hb/grey-2.webp",
          "/products/mesh/glanza-hb/grey-3.webp",
          "/products/mesh/glanza-hb/grey-4.webp",
          "/products/mesh/glanza-hb/grey-5.webp"
        ]
      },
      {
        "label": "White",
        "slug": "white",
        "images": [
          "/products/mesh/glanza-hb/white-1.webp",
          "/products/mesh/glanza-hb/white-2.webp",
          "/products/mesh/glanza-hb/white-3.webp",
          "/products/mesh/glanza-hb/white-4.webp"
        ]
      }
    ]
  },
  "glanza-mb": {
    "model": "Glanza",
    "back": "MB",
    "family": "mesh",
    "colours": [
      {
        "label": "Grey",
        "slug": "grey",
        "images": [
          "/products/mesh/glanza-mb/grey-1.webp",
          "/products/mesh/glanza-mb/grey-2.webp",
          "/products/mesh/glanza-mb/grey-3.webp",
          "/products/mesh/glanza-mb/grey-4.webp"
        ]
      },
      {
        "label": "White",
        "slug": "white",
        "images": [
          "/products/mesh/glanza-mb/white-1.webp",
          "/products/mesh/glanza-mb/white-2.webp",
          "/products/mesh/glanza-mb/white-3.webp",
          "/products/mesh/glanza-mb/white-4.webp"
        ]
      }
    ]
  },
  "hilite-hb": {
    "model": "Hilite",
    "back": "HB",
    "family": "ultra-luxury-mesh",
    "colours": [
      {
        "label": "Black",
        "slug": "black",
        "images": [
          "/products/ultra-luxury-mesh/hilite-hb/black-1.webp",
          "/products/ultra-luxury-mesh/hilite-hb/black-2.webp",
          "/products/ultra-luxury-mesh/hilite-hb/black-3.webp",
          "/products/ultra-luxury-mesh/hilite-hb/black-4.webp"
        ]
      }
    ]
  },
  "hilite-mb": {
    "model": "Hilite",
    "back": "MB",
    "family": "ultra-luxury-mesh",
    "colours": [
      {
        "label": "Black",
        "slug": "black",
        "images": [
          "/products/ultra-luxury-mesh/hilite-mb/black-1.webp",
          "/products/ultra-luxury-mesh/hilite-mb/black-2.webp",
          "/products/ultra-luxury-mesh/hilite-mb/black-3.webp",
          "/products/ultra-luxury-mesh/hilite-mb/black-4.webp"
        ]
      }
    ]
  },
  "mustang-mb": {
    "model": "Mustang",
    "back": "MB",
    "family": "ultra-luxury-mesh",
    "colours": [
      {
        "label": "Studio",
        "slug": "studio",
        "images": [
          "/products/ultra-luxury-mesh/mustang-mb/studio-1.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-2.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-3.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-4.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-5.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-6.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-7.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-8.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-9.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-10.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-11.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-12.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-13.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-14.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-15.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-16.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-17.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-18.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-19.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-20.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-21.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-22.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-23.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-24.webp",
          "/products/ultra-luxury-mesh/mustang-mb/studio-25.webp"
        ]
      }
    ]
  },
  "mustang-hb": {
    "model": "Mustang",
    "back": "HB",
    "family": "ultra-luxury-mesh",
    "colours": [
      {
        "label": "Black with Black",
        "slug": "black-with-black",
        "images": [
          "/products/ultra-luxury-mesh/mustang-hb/black-with-black-1.webp",
          "/products/ultra-luxury-mesh/mustang-hb/black-with-black-2.webp",
          "/products/ultra-luxury-mesh/mustang-hb/black-with-black-3.webp",
          "/products/ultra-luxury-mesh/mustang-hb/black-with-black-4.webp"
        ]
      },
      {
        "label": "Black with Blue",
        "slug": "black-with-blue",
        "images": [
          "/products/ultra-luxury-mesh/mustang-hb/black-with-blue-1.webp",
          "/products/ultra-luxury-mesh/mustang-hb/black-with-blue-2.webp",
          "/products/ultra-luxury-mesh/mustang-hb/black-with-blue-3.webp",
          "/products/ultra-luxury-mesh/mustang-hb/black-with-blue-4.webp"
        ]
      },
      {
        "label": "Black with Green",
        "slug": "black-with-green",
        "images": [
          "/products/ultra-luxury-mesh/mustang-hb/black-with-green-1.webp",
          "/products/ultra-luxury-mesh/mustang-hb/black-with-green-2.webp",
          "/products/ultra-luxury-mesh/mustang-hb/black-with-green-3.webp",
          "/products/ultra-luxury-mesh/mustang-hb/black-with-green-4.webp"
        ]
      },
      {
        "label": "Black with Grey",
        "slug": "black-with-grey",
        "images": [
          "/products/ultra-luxury-mesh/mustang-hb/black-with-grey-1.webp",
          "/products/ultra-luxury-mesh/mustang-hb/black-with-grey-2.webp",
          "/products/ultra-luxury-mesh/mustang-hb/black-with-grey-3.webp",
          "/products/ultra-luxury-mesh/mustang-hb/black-with-grey-4.webp"
        ]
      },
      {
        "label": "Black with Orange",
        "slug": "black-with-orange",
        "images": [
          "/products/ultra-luxury-mesh/mustang-hb/black-with-orange-1.webp",
          "/products/ultra-luxury-mesh/mustang-hb/black-with-orange-2.webp",
          "/products/ultra-luxury-mesh/mustang-hb/black-with-orange-3.webp",
          "/products/ultra-luxury-mesh/mustang-hb/black-with-orange-4.webp"
        ]
      },
      {
        "label": "Black with Red",
        "slug": "black-with-red",
        "images": [
          "/products/ultra-luxury-mesh/mustang-hb/black-with-red-1.webp",
          "/products/ultra-luxury-mesh/mustang-hb/black-with-red-2.webp",
          "/products/ultra-luxury-mesh/mustang-hb/black-with-red-3.webp",
          "/products/ultra-luxury-mesh/mustang-hb/black-with-red-4.webp"
        ]
      }
    ]
  },
  "optimus-pre-hb": {
    "model": "Optimus Pre",
    "back": "HB",
    "family": "ultra-luxury-mesh",
    "colours": [
      {
        "label": "Black",
        "slug": "black",
        "images": [
          "/products/ultra-luxury-mesh/optimus-pre-hb/black-1.webp",
          "/products/ultra-luxury-mesh/optimus-pre-hb/black-2.webp",
          "/products/ultra-luxury-mesh/optimus-pre-hb/black-3.webp",
          "/products/ultra-luxury-mesh/optimus-pre-hb/black-4.webp",
          "/products/ultra-luxury-mesh/optimus-pre-hb/black-5.webp"
        ]
      }
    ]
  },
  "optimus-pre-mb": {
    "model": "Optimus Pre",
    "back": "MB",
    "family": "ultra-luxury-mesh",
    "colours": [
      {
        "label": "Black",
        "slug": "black",
        "images": [
          "/products/ultra-luxury-mesh/optimus-pre-mb/black-1.webp",
          "/products/ultra-luxury-mesh/optimus-pre-mb/black-2.webp",
          "/products/ultra-luxury-mesh/optimus-pre-mb/black-3.webp"
        ]
      }
    ]
  },
  "bubble-mb": {
    "model": "Bubble",
    "back": "MB",
    "family": "task-mesh",
    "colours": [
      {
        "label": "Black",
        "slug": "black",
        "images": [
          "/products/task-mesh/bubble-mb/black-1.webp",
          "/products/task-mesh/bubble-mb/black-2.webp",
          "/products/task-mesh/bubble-mb/black-3.webp",
          "/products/task-mesh/bubble-mb/black-4.webp"
        ]
      },
      {
        "label": "Black with Blue",
        "slug": "black-with-blue",
        "images": [
          "/products/task-mesh/bubble-mb/black-with-blue-1.webp",
          "/products/task-mesh/bubble-mb/black-with-blue-2.webp",
          "/products/task-mesh/bubble-mb/black-with-blue-3.webp",
          "/products/task-mesh/bubble-mb/black-with-blue-4.webp"
        ]
      },
      {
        "label": "Black with Green",
        "slug": "black-with-green",
        "images": [
          "/products/task-mesh/bubble-mb/black-with-green-1.webp",
          "/products/task-mesh/bubble-mb/black-with-green-2.webp",
          "/products/task-mesh/bubble-mb/black-with-green-3.webp",
          "/products/task-mesh/bubble-mb/black-with-green-4.webp"
        ]
      },
      {
        "label": "Black with Grey",
        "slug": "black-with-grey",
        "images": [
          "/products/task-mesh/bubble-mb/black-with-grey-1.webp",
          "/products/task-mesh/bubble-mb/black-with-grey-2.webp",
          "/products/task-mesh/bubble-mb/black-with-grey-3.webp",
          "/products/task-mesh/bubble-mb/black-with-grey-4.webp",
          "/products/task-mesh/bubble-mb/black-with-grey-5.webp"
        ]
      },
      {
        "label": "Black with Orange",
        "slug": "black-with-orange",
        "images": [
          "/products/task-mesh/bubble-mb/black-with-orange-1.webp",
          "/products/task-mesh/bubble-mb/black-with-orange-2.webp",
          "/products/task-mesh/bubble-mb/black-with-orange-3.webp",
          "/products/task-mesh/bubble-mb/black-with-orange-4.webp"
        ]
      },
      {
        "label": "Black with Red",
        "slug": "black-with-red",
        "images": [
          "/products/task-mesh/bubble-mb/black-with-red-1.webp",
          "/products/task-mesh/bubble-mb/black-with-red-2.webp",
          "/products/task-mesh/bubble-mb/black-with-red-3.webp",
          "/products/task-mesh/bubble-mb/black-with-red-4.webp"
        ]
      },
      {
        "label": "Grey with Blue",
        "slug": "grey-with-blue",
        "images": [
          "/products/task-mesh/bubble-mb/grey-with-blue-1.webp",
          "/products/task-mesh/bubble-mb/grey-with-blue-2.webp",
          "/products/task-mesh/bubble-mb/grey-with-blue-3.webp"
        ]
      },
      {
        "label": "Grey with Green",
        "slug": "grey-with-green",
        "images": [
          "/products/task-mesh/bubble-mb/grey-with-green-1.webp",
          "/products/task-mesh/bubble-mb/grey-with-green-2.webp",
          "/products/task-mesh/bubble-mb/grey-with-green-3.webp",
          "/products/task-mesh/bubble-mb/grey-with-green-4.webp"
        ]
      },
      {
        "label": "Grey with Grey",
        "slug": "grey-with-grey",
        "images": [
          "/products/task-mesh/bubble-mb/grey-with-grey-1.webp",
          "/products/task-mesh/bubble-mb/grey-with-grey-2.webp",
          "/products/task-mesh/bubble-mb/grey-with-grey-3.webp",
          "/products/task-mesh/bubble-mb/grey-with-grey-4.webp"
        ]
      },
      {
        "label": "Grey with Orange",
        "slug": "grey-with-orange",
        "images": [
          "/products/task-mesh/bubble-mb/grey-with-orange-1.webp",
          "/products/task-mesh/bubble-mb/grey-with-orange-2.webp",
          "/products/task-mesh/bubble-mb/grey-with-orange-3.webp",
          "/products/task-mesh/bubble-mb/grey-with-orange-4.webp"
        ]
      },
      {
        "label": "Grey with Red",
        "slug": "grey-with-red",
        "images": [
          "/products/task-mesh/bubble-mb/grey-with-red-1.webp",
          "/products/task-mesh/bubble-mb/grey-with-red-2.webp",
          "/products/task-mesh/bubble-mb/grey-with-red-3.webp",
          "/products/task-mesh/bubble-mb/grey-with-red-4.webp"
        ]
      },
      {
        "label": "White with Blue",
        "slug": "white-with-blue",
        "images": [
          "/products/task-mesh/bubble-mb/white-with-blue-1.webp",
          "/products/task-mesh/bubble-mb/white-with-blue-2.webp",
          "/products/task-mesh/bubble-mb/white-with-blue-3.webp",
          "/products/task-mesh/bubble-mb/white-with-blue-4.webp"
        ]
      },
      {
        "label": "White with Green",
        "slug": "white-with-green",
        "images": [
          "/products/task-mesh/bubble-mb/white-with-green-1.webp",
          "/products/task-mesh/bubble-mb/white-with-green-2.webp"
        ]
      }
    ]
  },
  "yaris-hb": {
    "model": "Yaris",
    "back": "HB",
    "family": "special-luxury-mesh",
    "colours": [
      {
        "label": "Black with Black Flap",
        "slug": "black-with-black-flap",
        "images": [
          "/products/special-luxury-mesh/yaris-hb/black-with-black-flap-1.webp",
          "/products/special-luxury-mesh/yaris-hb/black-with-black-flap-2.webp",
          "/products/special-luxury-mesh/yaris-hb/black-with-black-flap-3.webp"
        ]
      },
      {
        "label": "Black with Blue Flap",
        "slug": "black-with-blue-flap",
        "images": [
          "/products/special-luxury-mesh/yaris-hb/black-with-blue-flap-1.webp",
          "/products/special-luxury-mesh/yaris-hb/black-with-blue-flap-2.webp",
          "/products/special-luxury-mesh/yaris-hb/black-with-blue-flap-3.webp",
          "/products/special-luxury-mesh/yaris-hb/black-with-blue-flap-4.webp"
        ]
      },
      {
        "label": "Black with Green Flap",
        "slug": "black-with-green-flap",
        "images": [
          "/products/special-luxury-mesh/yaris-hb/black-with-green-flap-1.webp",
          "/products/special-luxury-mesh/yaris-hb/black-with-green-flap-2.webp",
          "/products/special-luxury-mesh/yaris-hb/black-with-green-flap-3.webp",
          "/products/special-luxury-mesh/yaris-hb/black-with-green-flap-4.webp"
        ]
      },
      {
        "label": "Black with Grey Flap",
        "slug": "black-with-grey-flap",
        "images": [
          "/products/special-luxury-mesh/yaris-hb/black-with-grey-flap-1.webp",
          "/products/special-luxury-mesh/yaris-hb/black-with-grey-flap-2.webp",
          "/products/special-luxury-mesh/yaris-hb/black-with-grey-flap-3.webp",
          "/products/special-luxury-mesh/yaris-hb/black-with-grey-flap-4.webp"
        ]
      },
      {
        "label": "Black with Orange Flap",
        "slug": "black-with-orange-flap",
        "images": [
          "/products/special-luxury-mesh/yaris-hb/black-with-orange-flap-1.webp",
          "/products/special-luxury-mesh/yaris-hb/black-with-orange-flap-2.webp",
          "/products/special-luxury-mesh/yaris-hb/black-with-orange-flap-3.webp",
          "/products/special-luxury-mesh/yaris-hb/black-with-orange-flap-4.webp"
        ]
      },
      {
        "label": "Black with Red Flap",
        "slug": "black-with-red-flap",
        "images": [
          "/products/special-luxury-mesh/yaris-hb/black-with-red-flap-1.webp",
          "/products/special-luxury-mesh/yaris-hb/black-with-red-flap-2.webp",
          "/products/special-luxury-mesh/yaris-hb/black-with-red-flap-3.webp"
        ]
      }
    ]
  },
  "yaris-mb": {
    "model": "Yaris",
    "back": "MB",
    "family": "special-luxury-mesh",
    "colours": [
      {
        "label": "Black",
        "slug": "black",
        "images": [
          "/products/special-luxury-mesh/yaris-mb/black-1.webp",
          "/products/special-luxury-mesh/yaris-mb/black-2.webp",
          "/products/special-luxury-mesh/yaris-mb/black-3.webp"
        ]
      }
    ]
  }
};
